server:
  port: 10021

spring:
  application:
    name: "book"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cloud_study
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://eureka02:10032/eureka, http://eureka01:10031/eureka