spring:
  application:
    name: "account"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cloud_study
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update